project:
  type: website
  output-dir: docs

website:
  title: "shawnji3.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Description.qmd
        text: Description
      - href: courses.qmd
        text: Courses

format:
  html:
    theme: faltly
    css: styles.css
    toc: true

editor: visual

